[browser]
# Removed serverAddress to allow cloud deployment
gatherUsageStats = false

[theme]
# Dark mode theme settings
base = "dark"
primaryColor = "#4CAF50"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableStaticServing = true
enableCORS = false
enableXsrfProtection = false 