[server]
# The script path is now app.py instead of house_prediction_app.py
scriptPath = "app.py"

[browser]
# Auto-open the browser when the server starts
serverAddress = "localhost"
gatherUsageStats = false

[theme]
# Dark mode theme settings
base = "dark"
primaryColor = "#4CAF50"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif" 